//characters
export const GET_CHARACTERS_START = "GET_CHARACTERS_START";
export const GET_CHARACTERS_SUCCES = "GET_CHARACTERS_SUCCES";
export const GET_CHARACTERS_ERROR = "GET_CHARACTERS_ERROR";
export const REMOVE_CHARACTER = "REMOVE_CHARACTER";
